name: Daily ETL Run

on:
  #schedule:
  #  - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL process
      run: |
        python etl_process.py --output-file output.json